export default [
  '--disable-setuid-sandbox',
  '--start-maximized',
  '--disable-infobars',
  '--disable-gpu',
  '--force-device-scale-factor=0.7',
  '--no-sandbox',
  '--disable-extensions',
  '--disable-dev-shm-usage',
  '--disable-accelerated-2d-canvas',
  '--no-zygote',
  '--no-first-run',
  '--disable-default-apps',
  '--hide-scrollbars',
  '--mute-audio',
  '--disable-software-rasterizer',
];